# Sample kubeconfig
apiVersion: v1
kind: Config
preferences: {}

clusters:
- name: proxy-cluster
  cluster:
    server: https://kube.mydomain.us

users:
- name: proxy-user
  user:
    token: "unused"

contexts:
- name: proxy-worker
  context:
    cluster: proxy-cluster
    user: proxy-user
    namespace: cloudflared

current-context: proxy-worker
